name: CI/CD - Deploy .NET Backend to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Change if you're using a different .NET version

      - name: Publish .NET app
        run: dotnet publish -c Release -o published APIs.csproj

      - name: Clear temp deploy folder on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /tmp/aurora-backend && mkdir -p /tmp/aurora-backend

      - name: Copy build to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "published/*"
          target: "/tmp/aurora-backend"

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Clearing existing backend files..."
            sudo rm -rf /var/www/aurora-backend/*
            echo "Deploying new backend build..."
            sudo cp -r /tmp/aurora-backend/* /var/www/aurora-backend/
            echo "Reloading systemd and restarting services..."
            sudo systemctl daemon-reload
            sudo systemctl restart aurora-backend.service
            echo "Restarting Nginx..."
            sudo nginx -t && sudo systemctl restart nginx
